using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class VRInputTest : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {

        if (VRInput.A) Debug.Log("A押した");
        if (VRInput.B) Debug.Log("B押した");
        if (VRInput.X) Debug.Log("X押した");
        if (VRInput.Y) Debug.Log("Y押した");
        if (VRInput.RGrip) Debug.Log("右グリップ");
        if (VRInput.LGrip) Debug.Log("左グリップ");
        if (VRInput.RTrigger) Debug.Log("右トリガー");
        if (VRInput.LTrigger) Debug.Log("左トリガー");

        Debug.Log("右スティック　：　" + VRInput.RStick.ToString());
        Debug.Log("左スティック　：　" + VRInput.LStick.ToString());

    }
}
